/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master handler for getting a variables name, short name, etc.
*/
private["_var","_mode"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
_mode = [_this,1,-1,[0]] call BIS_fnc_param;
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "fishing": {"life_inv_fishingpoles"};
			case "coffee": {"life_inv_coffee"};
			case "turtlesoup": {"life_inv_turtlesoup"};
			case "donuts": {"life_inv_donuts"};
			case "fuelE": {"life_inv_fuelE"};
			case "fuelF": {"life_inv_fuelF"};
			case "money": {"life_cash"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "iron_r": {"life_inv_ironr"};
			case "copper_r": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "salt_r": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondr"};
			case "cocaine": {"life_inv_coke"};
			case "cocainep": {"life_inv_cokep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "goldbar": {"life_inv_goldbar"};
			case "lsdu": {"life_inv_lsdu"};
			case "lsdp": {"life_inv_lsdp"};
			case "mdmau": {"life_inv_mdmau"};
			case "mdmap": {"life_inv_mdmap"};
			case "cracku": {"life_inv_cracku"};
			case "crackp": {"life_inv_crackp"};
			case "goldu": {"life_inv_goldu"};
			case "goldp": {"life_inv_goldp"};
			case "rubyu": {"life_inv_rubyu"};
			case "rubyp": {"life_inv_rubyp"};
			case "emeraldu": {"life_inv_emeraldu"};
			case "emeraldp": {"life_inv_emeraldp"};
			case "ganascia": {"life_inv_ganascia"};
			case "speedtrap": {"life_inv_speedtrap"};
			case "speedtrapdetector": {"life_inv_speedtrapdetector"};
			case "laptop": {"life_inv_laptop"};
			case "fuelManipulator": {"life_inv_fuelManipulator"};
			case "fuelPipe": {"life_inv_fuelPipe"};
			case "tenaglie": {"life_inv_tenaglie"};
			case "storagesmall": {"life_inv_storagesmall"};
            case "storagebig": {"life_inv_storagebig"};
			case "bank_money": {"life_inv_bankmoney"};
			case "cannabisSeed": {"life_inv_cannabisSeed"};
			case "cocaineSeed": {"life_inv_cocaineSeed"};
			case "Land_Icebox_F": {"Land_Icebox_F"};
			case "Land_TableDesk_F": {"Land_TableDesk_F"};
			case "tavolo": {"life_inv_tavolo"};
			case "luppolo": {"life_inv_luppolo"};
			case "tartaruga": {"life_inv_tartaruga"};
			case "rame": {"life_inv_rame"};
			case "canapa": {"life_inv_canapa"};
			case "alluminio": {"life_inv_alluminio"};
			case "papavero": {"life_inv_papavero"};
			case "ferro": {"life_inv_ferro"};
			case "petrolio": {"life_inv_petrolio"};
			case "oro": {"life_inv_oro"};
			case "platino": {"life_inv_platino"};
			case "cocaina": {"life_inv_cocaina"};
			case "life_inv_uranio": {"life_inv_uranio"};
			case "birra": {"life_inv_birra"};
			case "ldrame": {"life_inv_ldrame"};
			case "fdcanapa": {"life_inv_fdcanapa"};
			case "marijuana": {"life_inv_marijuana"};
			case "ldalluminio": {"life_inv_ldalluminio"};
			case "morfina": {"life_inv_morfina"};
			case "eroina": {"life_inv_eroina"};
			case "ldferro": {"life_inv_ldferro"};
			case "benzina": {"life_inv_benzina"};
			case "napalm": {"life_inv_napalm"};
			case "ldoro": {"life_inv_ldoro"};
			case "ldplatino": {"life_inv_ldplatino"};
			case "cocainapura": {"life_inv_cocainapura"};
			case "uranioarricchito": {"life_inv_uranioarricchito"};		
			case "obirra": {"life_inv_obirra"};
			case "orame": {"life_inv_orame"};
			case "ocanapa": {"life_inv_ocanapa"};
			case "omarijuana": {"life_inv_omarijuana"};
			case "oalluminio": {"life_inv_oalluminio"};
			case "omorfina": {"life_inv_omorfina"};
			case "oeroina": {"life_inv_oeroina"};
			case "oferro": {"life_inv_oferro"};
			case "obenzina": {"life_inv_obenzina"};
			case "onapalm": {"life_inv_onapalm"};
			case "oplatino": {"life_inv_oplatino"};
			case "ococainapura": {"life_inv_ococainapura"};
			case "ooro": {"life_inv_ooro"};
		};
	};
	
	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_tavolo": {"tavolo"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_fishingpoles": {"fishing"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_turtlesoup": {"turtlesoup"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelE": {"fuelE"};
			case "life_inv_fuelF": {"fuelF"};
			case "life_cash": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"iron_r"};
			case "life_inv_copperr": {"copper_r"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondr": {"diamondc"};
			case "life_inv_saltr": {"salt_r"};
			case "life_inv_coke": {"cocaine"};
			case "life_inv_cokep": {"cocainep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_lsdu": {"lsdu"};
			case "life_inv_lsdp": {"lsdp"};
			case "life_inv_mdmau": {"mdmau"};
			case "life_inv_mdmap": {"mdmap"};
			case "life_inv_cracku": {"cracku"};
			case "life_inv_crackp": {"crackp"};
			case "life_inv_goldu": {"goldu"};
			case "life_inv_goldp": {"goldp"};
			case "life_inv_rubyu": {"rubyu"};
			case "life_inv_rubyp": {"rubyp"};
			case "life_inv_emeraldu": {"emeraldu"};
			case "life_inv_emeraldp": {"emeraldp"};
			case "life_inv_ganascia": {"ganascia"};
			case "life_inv_speedtrap": {"speedtrap"};
			case "life_inv_speedtrapdetector": {"speedtrapdetector"};
			case "life_inv_laptop": {"laptop"};
			case "life_inv_fuelManipulator": {"fuelManipulator"};
			case "life_inv_fuelPipe": {"fuelPipe"};
			case "life_inv_tenaglie": {"tenaglie"};
			case "life_inv_storagesmall": {"storagesmall"};
            case "life_inv_storagebig": {"storagebig"};
			case "life_inv_bankmoney": {"bank_money"};
			case "life_inv_cannabisSeed": {"cannabisSeed"};
			case "life_inv_cocaineSeed": {"cocaineSeed"};
			case "Land_Icebox_F": {"Land_Icebox_F"};
			case "Land_TableDesk_F": {"Land_TableDesk_F"};
			case "life_inv_luppolo": {"luppolo"};
			case "life_inv_tartaruga": {"tartaruga"};
			case "life_inv_rame": {"rame"};
			case "life_inv_canapa": {"canapa"};
			case "life_inv_alluminio": {"alluminio"};
			case "life_inv_papavero": {"papavero"};
			case "life_inv_ferro": {"ferro"};
			case "life_inv_petrolio": {"petrolio"};
			case "life_inv_oro": {"oro"};
			case "life_inv_platino": {"platino"};
			case "life_inv_cocaina": {"cocaina"};
			case "life_inv_uranio": {"uranio"};
			case "life_inv_birra": {"birra"};
			case "life_inv_ldrame": {"ldrame"};
			case "life_inv_fdcanapa": {"fdcanapa"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_ldalluminio": {"ldalluminio"};
			case "life_inv_morfina": {"morfina"};
			case "life_inv_eroina": {"eroina"};
			case "life_inv_ldferro": {"ldferro"};
			case "life_inv_benzina": {"benzina"};
			case "life_inv_napalm": {"napalm"};
			case "life_inv_ldoro": {"ldoro"};
			case "life_inv_ldplatino": {"ldplatino"};
			case "life_inv_cocainapura": {"cocainapura"};
			case "life_inv_uranioarricchito": {"uranioarricchito"};	
			case "life_inv_obirra": {"obirra"};
			case "life_inv_orame": {"orame"};
			case "life_inv_ocanapa": {"ocanapa"};
			case "life_inv_omarijuana": {"omarijuana"};
			case "life_inv_oalluminio": {"oalluminio"};
			case "life_inv_omorfina": {"omorfina"};
			case "life_inv_oeroina": {"oeroina"};
			case "life_inv_oferro": {"oferro"};
			case "life_inv_obenzina": {"obenzina"};
			case "life_inv_onapalm": {"onapalm"};
			case "life_inv_oplatino": {"oplatino"};
			case "life_inv_ococainapura": {"ococainapura"};
			case "life_inv_ooro": {"ooro"};
		};
	};
};
